const { loadCommands } = require('./dist/bot/commands/index.js');
const cmds = loadCommands();
const mock = { reply: (t) => console.log('REPLY:', t), author: '123@c.us', from: '123@c.us' };
(async () => {
  console.log('antispam 1');
  await cmds.get('antispam').execute(mock, null, []);
  console.log('antispam 2');
  await cmds.get('antispam').execute(mock, null, []);
  console.log('conselho');
  await cmds.get('conselho').execute(mock, null, []);
  console.log('conselhob');
  await cmds.get('conselhob').execute(mock, null, []);
  console.log('aleatoria txt');
  await cmds.get('aleatoria').execute(mock, null, []);
  console.log('aleatoria num');
  await cmds.get('aleatoria').execute(mock, null, ['num']);
  console.log('forca start');
  await cmds.get('forca').execute(mock, null, []);
  console.log('forca guess A');
  await cmds.get('forca').execute(mock, null, ['a']);
  console.log('forca reset');
  await cmds.get('forca').execute(mock, null, ['reset']);
})();
